### ISSUE TITLE
More sources

### ISSUE THREAD

**Issue by reddit-is-fun** [zant95/hosts-update#1]
The script should use more sources, for example uBlock Origin also comes with [EasyPrivacy] (https://easylist-downloads.adblockplus.org/easyprivacy.txt) and in my opinion also [Fanboy’s Enhanced Tracking List‎] (https://www.fanboy.co.nz/enhancedstats.txt) should be included
Also, I'd like to see an optional version with [Fanboy’s Annoyance List] (https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt) and [Anti-ThirdpartySocial] (https://www.fanboy.co.nz/fanboy-antifacebook.txt) list to get rid of social media plugins. 

My other suggestions:
- Spam404‎: https://spam404bl.com/spam404scamlist.txt
- Basic tracking list by Disconnect‎: https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
-  Malvertising filter list by Disconnect‎: https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
-  Adblock Warning Removal List‎: https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
- And maybe 'EU: Prebake - Filter Obtrusive Cookie Notices' for the users in EU: https://github.com/liamja/Prebake

**Comment by zant95** [comment]
Except Disconnect, the lists that you mention are for Adblock Plus and uBlock. I can't add them because they are incompatible with the hosts file, which only supports domain names.

**Comment by reddit-is-fun** [comment]
@zant95 Sorry, I wasn't aware of that. I thought that there were also domains in those filter lists.
